import { getDatabase, ref, query, orderByChild, startAt, get } from '@firebase/database';
import { subDays, subWeeks, subMonths } from 'date-fns';
import { Resend } from 'resend';

// Note: Using API keys on the frontend is insecure as they are bundled into the source code.
// For production, it is highly recommended to trigger this via a backend or Cloud Function.
const resend = new Resend(process.env.REACT_APP_RESEND_API_KEY);

/**
 * Service to handle manual generation of project digests.
 */
export const AdminReportService = {
  /**
   * Fetches data for the selected duration and triggers an email report.
   * @param {string} durationType - 'days' | 'weeks' | 'months'
   * @param {number} unit - The number of days/weeks/months (e.g., 1 day, 2 weeks)
   */
  async sendManualDigest(durationType, unit = 1) {
    const adminEmailsStr = process.env.REACT_APP_ADMIN_EMAILS || '';
    const adminEmails = adminEmailsStr.split(',').map(email => email.trim()).filter(Boolean);

    const db = getDatabase();
    const now = new Date();
    let startTime;

    // Calculate start time based on duration
    switch (durationType) {
      case 'days':
        startTime = subDays(now, unit).getTime();
        break;
      case 'weeks':
        startTime = subWeeks(now, unit).getTime();
        break;
      case 'months':
        startTime = subMonths(now, unit).getTime();
        break;
      default:
        throw new Error("Invalid duration type. Use 'days', 'weeks', or 'months'.");
    }

    try {
      // Fetch Import Logs
      const importLogsRef = ref(db, 'project/logs/imports');
      const importQuery = query(importLogsRef, orderByChild('timestamp'), startAt(startTime));
      const importSnap = await get(importQuery);

      // Fetch Export Logs
      const exportLogsRef = ref(db, 'project/logs/exports');
      const exportQuery = query(exportLogsRef, orderByChild('timestamp'), startAt(startTime));
      const exportSnap = await get(exportQuery);

      const digestData = {
        period: `${unit} ${durationType}`,
        generatedAt: now.getTime(),
        imports: importSnap.val() || {},
        exports: exportSnap.val() || {},
        summary: {
          totalImports: importSnap.exists() ? Object.keys(importSnap.val()).length : 0,
          totalExports: exportSnap.exists() ? Object.keys(exportSnap.val()).length : 0,
        }
      };

      return await this._triggerEmailFunction(adminEmails, digestData);
    } catch (error) {
      console.error("Failed to generate manual report:", error);
      throw error;
    }
  },

  /**
   * Internal method to call your email backend/cloud function.
   */
  async _triggerEmailFunction(emails, data) {
    if (!emails || emails.length === 0) {
      throw new Error("No admin emails found in environment variables.");
    }

    console.log(`Triggering individual emails via Resend to: ${emails.join(', ')}`);

    try {
      // Map each email to a separate send promise to ensure 3 distinct fires
      const emailPromises = emails.map(email => 
        resend.emails.send({
          from: 'Reports <onboarding@resend.dev>', // Replace with your verified domain in production
          to: email,
          subject: `Project Digest: Last ${data.period}`,
          html: `
            <div style="font-family: sans-serif; max-width: 600px; margin: auto; border: 1px solid #eee; padding: 20px;">
              <h1 style="color: #333;">Project Digest Report</h1>
              <p>This is a manual report generated by an admin.</p>
              <p><strong>Period:</strong> Last ${data.period}</p>
              <p><strong>Generated At:</strong> ${new Date(data.generatedAt).toLocaleString()}</p>
              <hr style="border: 0; border-top: 1px solid #eee;" />
              <h3>Data Summary</h3>
              <ul style="list-style: none; padding: 0;">
                <li style="padding: 10px 0; border-bottom: 1px solid #f9f9f9;">✅ <strong>Total Imports:</strong> ${data.summary.totalImports}</li>
                <li style="padding: 10px 0; border-bottom: 1px solid #f9f9f9;">📤 <strong>Total Exports:</strong> ${data.summary.totalExports}</li>
              </ul>
              <p style="font-size: 12px; color: #999; margin-top: 20px;">
                Sent to: ${email}
              </p>
            </div>
          `
        })
      );

      await Promise.all(emailPromises);

      return { success: true, message: "Report sent to admins via Resend." };
    } catch (error) {
      console.error("Resend API error:", error);
      throw new Error("Failed to send email via Resend.");
    }
  }
};